export const AREAS_OF_NEED = [
  "General Donation",
  "National Secretariat",
  "Building Project",
  "Wholeness Missions",
  "Wholeness Journal",
  "Institute of Medical Missions (IMM)",
  "Institute for Excellence in Healthcare and Leadership (IfEHL)",
  "Touch Magazine",
  "CMDA Nigeria Join Conference",
];

export const AREAS_OF_NEED_GLOBAL = [
  "General Donation",
  "Missions",
  "Regional Meeting",
  "Administration",
  "Building Project",
  "CMDA Nigeria Join Conference",
];

export const PAYPAL_CURRENCIES = [
  { currency: "Australian Dollar", code: "AUD" },
  // { currency: "Brazilian Real", code: "BRL" },
  { currency: "Canadian Dollar", code: "CAD" },
  // { currency: "Czech Koruna", code: "CZK" },
  // { currency: "Danish Krone", code: "DKK" },
  { currency: "Euro", code: "EUR" },
  // { currency: "Hong Kong Dollar", code: "HKD" },
  // { currency: "Hungarian Forint", code: "HUF" },
  // { currency: "Israeli New Shekel", code: "ILS" },
  // { currency: "Japanese Yen", code: "JPY" },
  // { currency: "Malaysian Ringgit", code: "MYR" },
  // { currency: "Mexican Peso", code: "MXN" },
  // { currency: "New Taiwan Dollar", code: "TWD" },
  // { currency: "New Zealand Dollar", code: "NZD" },
  // { currency: "Norwegian Krone", code: "NOK" },
  // { currency: "Philippine Peso", code: "PHP" },
  // { currency: "Polish Złoty", code: "PLN" },
  { currency: "Pound Sterling", code: "GBP" },
  // { currency: "Russian Ruble", code: "RUB" },
  // { currency: "Singapore Dollar", code: "SGD" },
  // { currency: "Swedish Krona", code: "SEK" },
  // { currency: "Swiss Franc", code: "CHF" },
  // { currency: "Thai Baht", code: "THB" },
  { currency: "United States Dollar", code: "USD" },
];
