//   gender options
export const genderOptions = ["Male", "Female"].map((y) => ({ label: y, value: y.toLowerCase() }));

// admission year select option
export const admissionYearOptions = Array.from({ length: 10 }, (_, i) => new Date().getFullYear() - i).map((x) => ({
  label: x,
  value: x,
}));

// current year select option
export const currentYearOptions = [
  { value: "1st Year", label: "1st Year" },
  { value: "2nd Year", label: "2nd Year" },
  { value: "3rd Year", label: "3rd Year" },
  { value: "4th Year", label: "4th Year" },
  { value: "5th Year", label: "5th Year" },
  { value: "6th Year", label: "6th Year" },
  { value: "7th Year", label: "7th Year" },
  { value: "8th Year", label: "8th Year" },
];

export const studentChapterOptions = [
  "AAU/ISTH",
  "ABUADTH",
  "BUTH",
  "DELSUTH",
  "EKSUTH",
  "IUTH",
  "UITH",
  "LTH",
  "LUTH",
  "UNIMEDTH",
  "LASUTH",
  "UCH",
  "OAUTHc",
  "OOUTH",
  "UBTH",
  "ABSUTH",
  "COOUTH",
  "EBSUTH",
  "ESUTH",
  "GUTH",
  "IMSUTH",
  "UPTH",
  "NAUTH",
  "UCTH",
  "UNTH",
  "UUTH",
  "NDUTH",
  "ABUTH",
  "AKTH",
  "BDTH/KASU",
  "BHUTH",
  "BSUTH",
  "GSUTH",
  "JUTH",
  "UDUTH",
  "UMTH",
  "UATH",
].map((x) => ({
  label: x + " Chapter",
  value: x + " Chapter",
}));

export const doctorsRegionLists = [
  "Abia - Umahia",
  "Adamawa",
  "Akwa Ibom",
  "Anambra (NAUTH)",
  "Bauchi",
  "Bayelsa",
  "Benue",
  "Borno",
  "CMDA Uyo",
  "Delta",
  "Delta - DELSUTH, Oghara",
  "Delta FMC, Asaba",
  "Ebonyi",
  "Edo-Benin",
  "Edo-SHMB",
  "Edo-Irrua",
  "Ekiti - Ido",
  "Ekiti-Ado",
  "Enugu",
  "FCT Gwagwalada",
  "FCT Municipal",
  "Gombe",
  "Imo",
  "Kaduna - Kaduna",
  "Kaduna - Zaria",
  "Kano",
  "Kogi",
  "Kwara",
  "Lagos-Lasuth",
  "Lagos-Luth",
  "Nasarawa - Keffi",
  "Nasarawa - Lafiya",
  "Niger-Bida",
  "Ogun - Abeokuta",
  "Ogun - Shagamu",
  "Ondo - Owo",
  "ONDO – UNIMEDTH",
  "Osun-Ife",
  "Osun-Osogbo",
  "Oyo",
  "Plateau",
  "Rivers",
  "Sokoto",
  "Taraba",
  "Kebbi",
].map((x) => ({
  label: x,
  value: x,
}));
