import {
  MdMenu,
  MdKeyboardArrowUp,
  MdClose,
  MdLogout,
  MdOutlineSettings,
  MdStore,
  MdMessage,
  MdGroups2,
  MdPlayArrow,
  MdPerson,
  MdAudiotrack,
  MdAddShoppingCart,
  MdShoppingCart,
  MdViewModule,
  MdOutlineLocationOn,
  MdFilterList,
  MdOutlineAdd,
} from "react-icons/md";
import { FiBell, FiDownloadCloud } from "react-icons/fi";
import { HiBadgeCheck, HiDotsVertical, HiOutlineHome } from "react-icons/hi";
import {
  FaPlus,
  FaMinus,
  FaCheck,
  FaCheckCircle,
  FaEye,
  FaEyeSlash,
  FaRegCalendarAlt,
  FaCaretDown,
  FaChevronRight,
  FaArrowLeft,
  FaRegNewspaper,
  FaFacebookF,
  FaInstagram,
  FaLinkedin,
  FaWhatsapp,
  FaChevronLeft,
  FaAngleDoubleRight,
  FaAngleDoubleLeft,
  FaPrayingHands,
  FaCreditCard,
  FaYoutube,
} from "react-icons/fa";
import { AiOutlineDelete, AiOutlineFileText } from "react-icons/ai";
import {
  BsFileEarmarkImage,
  BsFiletypeDoc,
  BsFiletypePdf,
  BsFillFileEarmarkPdfFill,
  BsGlobe,
  BsPaperclip,
  BsPencil,
  BsSendFill,
  BsSortAlphaDownAlt,
  BsSortAlphaUp,
} from "react-icons/bs";
import { BiBriefcase, BiSortAlt2 } from "react-icons/bi";
import { RxCounterClockwiseClock } from "react-icons/rx";
import { IoList } from "react-icons/io5";
import { GoDotFill } from "react-icons/go";
import { FaXTwitter } from "react-icons/fa6";
const icons = {
  bell: <FiBell />,
  download: <FiDownloadCloud />,
  menu: <MdMenu />,
  verticalDots: <HiDotsVertical />,
  plus: <FaPlus />,
  minus: <FaMinus />,
  delete: <AiOutlineDelete />,
  doc: <BsFiletypeDoc />,
  image: <BsFileEarmarkImage />,
  file: <AiOutlineFileText />,
  pdf: <BsFillFileEarmarkPdfFill />,
  pdfAlt: <BsFiletypePdf />,
  check: <FaCheck />,
  checkAlt: <FaCheckCircle />,
  eye: <FaEye />,
  eyeSlash: <FaEyeSlash />,
  sort: <BiSortAlt2 />,
  ascending: <BsSortAlphaUp />,
  descending: <BsSortAlphaDownAlt />,
  arrowUp: <MdKeyboardArrowUp />,
  close: <MdClose />,
  logout: <MdLogout />,
  settings: <MdOutlineSettings />,
  home: <HiOutlineHome />,
  calendar: <FaRegCalendarAlt />,
  store: <MdStore />,
  message: <MdMessage />,
  group: <MdGroups2 />,
  play: <MdPlayArrow />,
  caretDown: <FaCaretDown />,
  person: <MdPerson />,
  chevronRight: <FaChevronRight />,
  chevronRightDouble: <FaAngleDoubleRight />,
  chevronLeft: <FaChevronLeft />,
  chevronLeftDouble: <FaAngleDoubleLeft />,
  verified: <HiBadgeCheck />,
  arrowLeft: <FaArrowLeft />,
  audio: <MdAudiotrack />,
  newspaper: <FaRegNewspaper />,
  cart: <MdShoppingCart />,
  cartAdd: <MdAddShoppingCart />,
  pencil: <BsPencil />,
  clockCounter: <RxCounterClockwiseClock />,
  send: <BsSendFill />,
  clip: <BsPaperclip />,
  list: <IoList />,
  grid: <MdViewModule />,
  dot: <GoDotFill />,
  facebook: <FaFacebookF />,
  twitter: <FaXTwitter />,
  instagram: <FaInstagram />,
  linkedIn: <FaLinkedin />,
  whatsapp: <FaWhatsapp />,
  location: <MdOutlineLocationOn />,
  globe: <BsGlobe />,
  pray: <FaPrayingHands />,
  filter: <MdFilterList />,
  card: <FaCreditCard />,
  add: <MdOutlineAdd />,
  youtube: <FaYoutube />,
  briefcase: <BiBriefcase />,
};

export default icons;
